import type { ServicePageContent } from "@/components/ServiceSubpage"

export const debarrasContent: ServicePageContent = {
  name: "Débarras",
  h1: "Débarras",
  lead: "On vide, on charge et on transporte. Cave, grenier, garage, appartement ou local.",
  quickInfoChips: ["Devis gratuit", "Intervention planifiée", "Évacuation / transport"],
  whatTitle: "Ce que l'on fait",
  whatText: "Nous intervenons pour débarrasser des espaces encombrés, déplacer des objets lourds et évacuer ce qui doit être transporté. Idéal pour gagner du temps et éviter la logistique.",
  examplesTitle: "Cas courants",
  examples: [
    "Débarras de cave, garage, grenier",
    "Appartement / maison (meubles, cartons, encombrants)",
    "Déplacement de matériel lourd",
    "Évacuation vers déchetterie / filière adaptée",
  ],
  howTitle: "Comment ça se passe",
  howSteps: [
    { title: "Demande", text: "décris le volume, l'accès, ajoute des photos si possible." },
    { title: "Planification", text: "créneau + estimation." },
    { title: "Intervention", text: "chargement, transport, nettoyage léger si prévu." },
  ],
  pricingTitle: "Tarifs",
  pricingText: "Le prix dépend surtout du volume, de l'accès et du temps sur place. Devis gratuit.",
  pricingBullets: ["Volume (m³) / quantité", "Accès (code d'entrée, digicode, etc.)", "Temps de manutention", "Distance / transport"],
  pricingLinkLabel: "Demander un devis",
  pricingLinkHref: "/contact",
  faqTitle: "FAQ",
  faq: [
    { q: "Dois-je être présent ?", a: "Idéalement oui au début. Ensuite, selon le cas, on peut opérer avec instructions." },
    { q: "Est-ce que vous démontez les meubles ?", a: "Oui si nécessaire. Indique-le dans la demande." },
    { q: "Vous pouvez intervenir en urgence ?", a: "Selon disponibilités. Indique \"urgent\" dans la demande." },
  ],
  finalCtaTitle: "Besoin d'un débarras ?",
  finalCtaParagraph: "Envoie ta demande, on te répond rapidement.",
}

export const transportLivraisonContent: ServicePageContent = {
  name: "Transport & livraison",
  h1: "Transport & livraison",
  lead: "Transport sécurisé de marchandises et livraison sur demande.",
  quickInfoChips: ["Devis gratuit", "Intervention planifiée", "Service local"],
  whatTitle: "Ce que l'on fait",
  whatText: "Nous assurons le transport de meubles, électroménager, palettes légères ou marchandises d'un point A à un point B, avec manutention si besoin. Idéal pour une livraison, un retrait en magasin ou un déplacement de matériel.",
  examplesTitle: "Cas courants",
  examples: [
    "Transport de meubles ou électroménager",
    "Palettes légères, marchandises",
    "Point A → point B",
    "Retrait magasin / livraison à domicile",
  ],
  howTitle: "Comment ça se passe",
  howSteps: [
    { title: "Demande", text: "formulaire ou téléphone : adresses, volume, contraintes." },
    { title: "Planification", text: "créneau + estimation du temps." },
    { title: "Intervention", text: "réalisation du transport et livraison sur place." },
  ],
  pricingTitle: "Tarifs",
  pricingText: "Le prix dépend de la distance, du volume et de la manutention. Devis gratuit.",
  pricingBullets: ["Distance / trajet", "Volume / quantité", "Manutention (chargement, déchargement)", "Contraintes d'accès"],
  pricingLinkLabel: "Demander un devis",
  pricingLinkHref: "/contact",
  faqTitle: "FAQ",
  faq: [
    { q: "Vous livrez où ?", a: "Nous intervenons en priorité en région locale. Précise ton adresse dans la demande." },
    { q: "Je peux faire retirer en magasin ?", a: "Oui, indique l'adresse de retrait et de livraison." },
    { q: "Combien de temps à l'avance réserver ?", a: "Selon disponibilités. Plus la demande est en avance, plus c'est simple à planifier." },
  ],
  finalCtaTitle: "Prêt à planifier un transport ?",
  finalCtaParagraph: "Décris ta demande, on te répond rapidement.",
}

export const installationManutentionContent: ServicePageContent = {
  name: "Installation & manutention",
  h1: "Installation & manutention",
  lead: "Mise en place, montage simple et déplacement d'objets lourds. On intervient pour installer ou déplacer ce dont vous avez besoin.",
  quickInfoChips: ["Devis gratuit", "Intervention planifiée", "Manutention"],
  whatTitle: "Ce que l'on fait",
  whatText: "Nous proposons une aide à l'installation et à la manutention : mise en place de mobilier, aide au déménagement, montage simple, déplacement d'objets lourds. Pour gagner du temps et éviter les efforts inutiles.",
  examplesTitle: "Cas courants",
  examples: [
    "Mise en place de mobilier",
    "Aide au déménagement (chargement / déchargement)",
    "Montage simple (meubles, étagères)",
    "Déplacement d'objets lourds",
  ],
  howTitle: "Comment ça se passe",
  howSteps: [
    { title: "Demande", text: "décris ce qu'il faut installer ou déplacer, accès, étage." },
    { title: "Planification", text: "créneau + estimation (temps, contraintes)." },
    { title: "Intervention", text: "réalisation sur place (installation, manutention)." },
  ],
  pricingTitle: "Tarifs",
  pricingText: "Le prix dépend du temps passé, des contraintes et de l'accès. Devis gratuit.",
  pricingBullets: ["Temps d'intervention", "Contraintes (étage, accès)", "Type de prestation (montage, manutention)"],
  pricingLinkLabel: "Demander un devis",
  pricingLinkHref: "/contact",
  faqTitle: "FAQ",
  faq: [
    { q: "Vous montez des meubles ?", a: "Oui, montage simple (meubles en kit, étagères). Pour du plus complexe, on en discute." },
    { q: "Je déménage, vous pouvez aider ?", a: "Oui, on peut assurer le chargement, le transport et le déchargement. Demande un devis." },
    { q: "Objet très lourd, c'est possible ?", a: "Oui, on est équipé pour la manutention. Décris l'objet et l'accès." },
  ],
  finalCtaTitle: "Besoin d'aide pour installer ou déplacer ?",
  finalCtaParagraph: "Décris ta demande, on te répond rapidement.",
}

export const recyclageDomicileContent: ServicePageContent = {
  name: "Recyclage à domicile",
  h1: "Recyclage à domicile",
  lead: "Bacs de tri à domicile et récupération selon votre abonnement. On simplifie le tri au quotidien.",
  quickInfoChips: ["Abonnement mensuel", "Bacs fournis", "Service local"],
  whatTitle: "Ce que l'on fait",
  whatText: "Nous mettons à disposition des bacs de tri et les récupérons selon la fréquence de votre abonnement. Papier, plastique, verre, métal : on s'occupe du dépôt et de l'échange des bacs (propres et désinfectés).",
  examplesTitle: "Cas courants",
  examples: [
    "Dépôt et échange de bacs à domicile",
    "Abonnement 1 à 4 passages par mois",
    "Tri : papier, plastique, verre, métal",
    "Bacs propres et désinfectés",
  ],
  howTitle: "Comment ça se passe",
  howSteps: [
    { title: "Demande", text: "choisis un abonnement adapté (voir les tarifs)." },
    { title: "Planification", text: "mise en place des bacs et calendrier des passages." },
    { title: "Intervention", text: "passage selon le rythme convenu, échange des bacs." },
  ],
  pricingTitle: "Tarifs",
  pricingText: "Tarification par abonnement (nombre de passages, type de bacs). Dès 20 CHF / mois.",
  pricingBullets: ["Nombre de passages par mois", "Type de bacs (p'tit bac, grand bac)", "Supplément échange p'tit bac ↔ grand bac"],
  pricingLinkLabel: "Voir les abonnements",
  pricingLinkHref: "/#pricing",
  faqTitle: "FAQ",
  faq: [
    { q: "Comment choisir mon abonnement ?", a: "Selon la quantité de déchets et la fréquence souhaitée. Voir la page Tarifs pour les formules." },
    { q: "Les bacs sont fournis ?", a: "Oui, nous fournissons et entretenons les bacs (propres, désinfectés)." },
    { q: "Je peux changer de formule ?", a: "Oui, on peut adapter le nombre de passages ou le type de bacs. Contacte-nous." },
  ],
  finalCtaTitle: "Prêt à simplifier ton tri ?",
  finalCtaParagraph: "Décris ta demande ou consulte les abonnements, on te répond rapidement.",
}
